### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by sibero80** [blacksmithlabs/orbit-bhyve-remote#1]
Hello Bill, I'm a home automation enthuiast looking to monitor home water usage.
The Orbit bhyve seems a good and mature hardware but so far I have not found a manufacturer that provides an api to integrate with applications like Home Assistant.

I have a couple of questions.

Does your implementation require internet connection?
Are there any methods to gather water flow?

Thank you!

**Comment by killermonk** [comment]
1) Yes. It requires an internet connection. It is a simple wrapper around Orbit's existing API, which requires an internet connection to access.
2) Nope. It currently does only 2 things: First, set/remove rain delay. Second, start/stop watering a specific zone.

It's just a very very simple wrapper around Orbit's existing API for only those two functions.
